import { ConfigProvider } from "antd";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { BorderOuterOutlined } from "@ant-design/icons";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ margin: 0 }}>
        <AntdRegistry>
          <ConfigProvider
            theme={{
              token: {},
              components: {
                Typography: {
                  colorTextBase: "#1677ff",
                },
              },
            }}
          >
            {children}
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
